name: Deploy API to Railway

on:
  push:
    branches: [ main ]

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Depedencies
        run: pip install -r requirements.txt
      - name: Build the application
        run: uvicorn app.main:app --host 0.0.0.0 --port 8000
      - name: Deploy Railway
        uses: railwayapp/actions@v1
        with:
          project: "worthy-bravery"
          token: ${{ secrets.RAILWAYKEY }}
          build: uvicorn app.main:app --host 0.0.0.0 --port 8000
          run_command: uvicorn app.main:app --host 0.0.0.0 --port 8000
